runPipeline('simplePipeline') {
  appName = 'basic-app'
  role = 'basic'
  platform = 'java'
  cookbookName = 'tc-basic'
  chefRepoUri = 'git@github.com:ThomasCookOnline/chef-repo'
  chefRepo {
     uri = 'git@github.com:ThomasCookOnline/chef-repo'
     credentials = 'abc123'
  }
}
